# Generated by Django 4.2.13 on 2024-07-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='对话记录',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('role', models.TextField()),
                ('展示content', models.TextField()),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
