# Generated by Django 4.2.13 on 2024-07-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_对话记录'),
    ]

    operations = [
        migrations.AddField(
            model_name='对话记录',
            name='不带入大模型对话中',
            field=models.BooleanField(default=False),
        ),
    ]
