# Generated by Django 4.2.13 on 2024-11-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_对话记录_negative_review_对话记录_positive_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='关键词',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_time', models.DateTimeField(auto_now=True)),
                ('关键词', models.TextField()),
                ('模块', models.TextField()),
                ('备注', models.TextField()),
            ],
        ),
    ]
