# Generated by Django 4.2.13 on 2024-09-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_对话记录_提交给大模型的playload_alter_对话记录_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNET新闻',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('标题', models.TextField()),
                ('标题中文翻译', models.TextField(null=True)),
                ('新闻发布日期', models.DateTimeField(auto_now_add=True)),
                ('url', models.TextField(null=True)),
                ('作者', models.TextField(null=True)),
                ('权限', models.TextField(null=True)),
                ('新闻内容', models.TextField(default=False)),
                ('摘要', models.TextField(default=False)),
                ('新闻内容中文翻译', models.TextField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
