# Generated by Django 4.2.13 on 2024-09-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cnet新闻'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnet新闻',
            name='新闻发布日期',
            field=models.DateTimeField(null=True),
        ),
    ]
