# Generated by Django 4.2.13 on 2024-07-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_对话记录_不带入大模型对话中'),
    ]

    operations = [
        migrations.AddField(
            model_name='对话记录',
            name='已结束',
            field=models.BooleanField(default=False),
        ),
    ]
