# Generated by Django 4.2.13 on 2024-10-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_销售入账记录_客户向量编码_销售入账记录_客户向量编码模型'),
    ]

    operations = [
        migrations.AlterField(
            model_name='对话记录',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='销售入账记录',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
