# Generated by Django 4.2.13 on 2024-07-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_展示content_对话记录_处理后content'),
    ]

    operations = [
        migrations.AddField(
            model_name='对话记录',
            name='提交给大模型的playload',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='对话记录',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='对话记录',
            name='处理后content',
            field=models.TextField(null=True),
        ),
    ]
