# Generated by Django 4.2.13 on 2024-11-11 02:33

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_对话记录_id_alter_销售入账记录_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='知识主表',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_time', models.DateTimeField(auto_now=True)),
                ('标题', models.TextField()),
                ('url', models.TextField()),
                ('创建时间', models.DateTimeField(blank=True, null=True)),
                ('作者', models.TextField(blank=True, null=True)),
                ('权限', models.TextField(blank=True, null=True)),
                ('向量编码', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('向量编码模型', models.TextField(default='bge-large-zh-v1.5')),
            ],
        ),
        migrations.CreateModel(
            name='知识详细表',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_time', models.DateTimeField(auto_now=True)),
                ('文本内容', models.TextField()),
                ('向量编码', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('向量编码模型', models.TextField(default='bge-large-zh-v1.5')),
                ('知识主表', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.知识主表')),
            ],
        ),
    ]
