# Generated by Django 4.2.13 on 2024-11-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_知识主表_创建时间'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='知识主表',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='知识主表',
            name='lastmodified_time',
        ),
        migrations.RemoveField(
            model_name='知识主表',
            name='作者',
        ),
        migrations.RemoveField(
            model_name='知识主表',
            name='权限',
        ),
        migrations.RemoveField(
            model_name='知识详细表',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='知识详细表',
            name='lastmodified_time',
        ),
    ]
