# Generated by Django 4.2.13 on 2024-11-11 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_知识主表_知识详细表'),
    ]

    operations = [
        migrations.AddField(
            model_name='知识详细表',
            name='内容在分段中的顺序',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='知识详细表',
            name='知识主表',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.知识主表'),
        ),
    ]
