# Generated by Django 4.2.13 on 2024-11-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_知识主表_模块_alter_知识主表_url_alter_知识主表_标题'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='知识主表',
            name='创建时间',
        ),
    ]
