# Generated by Django 4.2.13 on 2024-11-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_知识详细表_内容在分段中的顺序_alter_知识详细表_知识主表'),
    ]

    operations = [
        migrations.AddField(
            model_name='知识主表',
            name='模块',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='知识主表',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='知识主表',
            name='标题',
            field=models.TextField(blank=True, null=True),
        ),
    ]
