# Generated by Django 4.2.13 on 2024-11-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_知识主表_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='对话记录',
            name='negative_review',
            field=models.BooleanField(default=False, verbose_name='差评'),
        ),
        migrations.AddField(
            model_name='对话记录',
            name='positive_review',
            field=models.BooleanField(default=False, verbose_name='好评'),
        ),
    ]
